# Generated by Django 4.2.16 on 2025-02-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='記事のメイン画像をアップロード', null=True, upload_to='blog/featured/'),
        ),
    ]
