# Generated by Django 4.2.16 on 2025-04-07 02:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='記事のメイン画像をアップロード', max_length=255, null=True, verbose_name='featured image'),
        ),
    ]
