# Generated by Django 4.2.16 on 2024-09-15 08:51

import base.models.item_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=base.models.item_models.upload_image_to),
        ),
    ]
