# Generated by Django 4.2.16 on 2024-09-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_items',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='base.item'),
        ),
    ]
