# Generated by Django 4.2.16 on 2025-04-07 02:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='header_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='header image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='item image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile image'),
        ),
    ]
